import numpy as np
from acados_template import AcadosOcp, AcadosOcpSolver
from cubic_trajectory import generate_cubic_spline_trajectory
from model import export_kinematic_bicycle_model
import matplotlib.pyplot as plt
import casadi as ca
from scipy.interpolate import interp1d


def main():
    """
    Main function to run MPC using acados to track a trajectory generated by cubic splines.
    """

    # Create an OCP object to define the optimization problem
    ocp = AcadosOcp()

    # Load the kinematic bicycle model
    model = export_kinematic_bicycle_model()
    ocp.model = model

    # Define simulation parameters
    Tf = 2 # Total time horizon [s]
    N = 20    # Prediction horizon (number of intervals)
    nx = model.x.rows()  # Number of states
    nu = model.u.rows()  # Number of control inputs

    # Set the number of shooting intervals (prediction horizon)
    ocp.dims.N = N

    # Set the prediction horizon in the solver
    ocp.solver_options.N_horizon = N
    ocp.solver_options.tf = Tf

    # Define cost matrices
    Q = np.diag([1.0, 1.0, 0.5, 0.5])  # State cost
    R = np.diag([0.01, 0.01])              # Control cost
    Qf = np.diag([2.0, 2.0, 1.0, 1.0])  # Terminal state cost

    # Configure path cost
    ocp.cost.cost_type = 'NONLINEAR_LS'
    ocp.model.cost_y_expr = ca.vertcat(model.x, model.u)  # Cost depends on states and controls
    ocp.cost.yref = np.zeros(nx + nu)  # Reference trajectory (set later dynamically)
    ocp.cost.W = ca.diagcat(Q, R).full()  # Weighting matrix

    # Configure terminal cost
    ocp.cost.cost_type_e = 'NONLINEAR_LS'
    ocp.model.cost_y_expr_e = model.x  # Terminal cost depends on states only
    ocp.cost.yref_e = np.zeros(nx)  # Terminal reference trajectory
    ocp.cost.W_e = Qf

    # Define control constraints
    MAX_ACCEL = 1000.0       # Maximum acceleration [m/s^2]
    MAX_STEER = np.deg2rad(75.0)  # Maximum steering angle [rad]
    MAX_SPEED = 550.0 / 3.6  # Maximum speed [m/s]

    # Control bounds
    ocp.constraints.lbu = np.array([-MAX_ACCEL, -MAX_STEER])
    ocp.constraints.ubu = np.array([MAX_ACCEL, MAX_STEER])
    ocp.constraints.idxbu = np.array([0, 1])  # Indices of control constraints (acceleration, steering)

    # State constraints
    ocp.constraints.idxbx = np.array([2])  # Index for velocity (v)
    ocp.constraints.lbx = np.array([0.0])  # Minimum velocity
    ocp.constraints.ubx = np.array([MAX_SPEED])  # Maximum velocity

    # Initial state constraint
    ocp.constraints.x0 = np.zeros(nx)  # Set the initial state as zero

    # Solver settings
    ocp.solver_options.qp_solver = 'PARTIAL_CONDENSING_HPIPM'
    ocp.solver_options.hessian_approx = 'GAUSS_NEWTON'
    ocp.solver_options.integrator_type = 'ERK'
    ocp.solver_options.nlp_solver_type = 'SQP'

    # Create the solver
    ocp_solver = AcadosOcpSolver(ocp)

    # Define waypoints and generate a reference trajectory using cubic splines
    start_waypoint = [-6, 2]
    end_waypoint = [6, -3.5]

    waypoints = [
        start_waypoint,
        [-3.5, 1.5],
        [-3.2, 1.4],
        [-1.8, 1.8],
        [-1.8, 1.9],
        [0.2, 1.7],
        [0.5, 1.4],
        [2, -1],
        [2, -2.5],
        [3.5, -3],
        end_waypoint
    ]

    smooth_x, smooth_y, _ = generate_cubic_spline_trajectory(waypoints)

    # Log the track generated by the cubic trajectory
    print("Cubic Trajectory Points:")
    for x, y in zip(smooth_x, smooth_y):
        print(f"({x:.3f}, {y:.3f})")

    # Making sure initial state is set correctly
    smooth_x[0] = waypoints[0][0]
    smooth_y[0] = waypoints[0][1]

    # Set the initial state
    initial_state = np.array([smooth_x[0], smooth_y[0], 0.1, 0.5])  # [x, y, v, theta]
    ocp_solver.set(0, "x", initial_state)

    for i in range(N):
        if i < len(smooth_x):
            x_ref = smooth_x[i]
            y_ref_scalar = smooth_y[i]  # Avoid naming conflict
        else:
            x_ref = smooth_x[-1]
            y_ref_scalar = smooth_y[-1]
        y_ref_array = np.array([x_ref, y_ref_scalar, 10/3.6, 0.0, 0.0, 0.0])  # [x, y, v, theta, a, phi]
        ocp_solver.set(i, "yref", y_ref_array)
        print(f"Step {i}: x_ref={x_ref:.3f}, y_ref={y_ref_scalar:.3f}")

    # Define terminal reference trajectory in the OCP configuration
    ocp.cost.yref_e = np.array([smooth_x[-1], smooth_y[-1], 0.0, 0.0])  # Final state [x, y, v, theta]

    # Solve the OCP
    simX = np.zeros((N + 1, nx))
    simU = np.zeros((N, nu))
    status = ocp_solver.solve()
    ocp_solver.print_statistics()

    if status != 0:
        print(f"Solver failed with status {status}.")
        return

    # Extract the solution and log for debugging
    for i in range(N):
        simX[i, :] = ocp_solver.get(i, "x")  # Extract state at step i
        simU[i, :] = ocp_solver.get(i, "u")  # Extract control input at step i
        print(f"Step {i}: State {simX[i, :]}, Control {simU[i, :]}")  # Debugging output
    simX[N, :] = ocp_solver.get(N, "x")  # Extract final state
    print(f"Final State: {simX[N, :]}")

    # Ensure all states are properly extracted
    print("Complete State Trajectory:")
    print(simX)
    print("Complete Control Inputs:")
    print(simU)

    # Plot results
    plt.figure(figsize=(10, 8))
    plt.plot(smooth_x, smooth_y, "--r", label="Reference Trajectory")
    plt.plot(simX[1,:], simX[2,:], "-b", label="Optimized Trajectory (Dense)")
    plt.scatter(np.array(waypoints)[:, 0], np.array(waypoints)[:, 1], color="green", label="Waypoints")
    plt.xlabel("X [m]")
    plt.ylabel("Y [m]")
    plt.title("Unconstrained MPC Trajectory Tracking")
    plt.legend()
    plt.grid()
    plt.show()

    print("State Trajectory:\n", simX)
    print("Control Inputs:\n", simU)

if __name__ == "__main__":
    main()
